services:
  futuramaapi:
    build: .
    command: sh docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      - ALLOW_ORIGINS=*
      - DATABASE_URL=postgresql://futuramaapi:futuramaapi-psql-password@futuramaapi-postgres:5432/futuramaapi
      - TRUSTED_HOST=localhost
      - SECRET_KEY=PRODUCTION-SECRET-KEY
      - EMAIL_FROM_DEFAULT=default@from.email
      - EMAIL_HOST_USER=host-user
      - EMAIL_HOST=email-host
      - EMAIL_API_KEY=secret-api-key
      - REDISCLOUD_URL=redis://redis-admin:futuramaapi-redis-password@futuramaapi-redis:6379
      - SEND_EMAILS=false
    depends_on:
      - futuramaapi-postgres
      - futuramaapi-redis

  futuramaapi-postgres:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=futuramaapi
      - POSTGRES_PASSWORD=futuramaapi-psql-password
      - POSTGRES_DB=futuramaapi

  futuramaapi-redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass futuramaapi-redis-password
    volumes:
      - futuramaapi-redis:/data

volumes:
  postgres_data:
  futuramaapi-redis:
